[package]
authors = ["Yiwei Yang <victoryang00@ucsc.edu>"]
edition = "2021"
name = "ioring-rs"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]