name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-win:
    runs-on: self-hosted
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-msvc
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Run clippy
      run: cargo clippy
    
    - name: Run tests
      run: cargo test --all-features

    - name: Run example readme
      run: cargo run --package ioring-rs --example readme --all-features 

    - name: Run example tcp_echo
      run: cargo run --package ioring-rs --example tcp_echo --all-features 

    - name: Run example raw_api_read
      run: cargo run --package ioring-rs --example raw_api_read --all-features 
